CREATE TABLE [dbo].[MonitoredInstances] (
    [InstanceID]             INT           IDENTITY (1, 1) NOT NULL,
    [ServerID]               INT           NULL,
    [InstanceName]           VARCHAR (128) NOT NULL,
    [Environment]            VARCHAR (60)  NULL,
    [MonitorInstance]        BIT           CONSTRAINT [c_default_Monitor] DEFAULT ((1)) NULL,
    [Edition]                VARCHAR (128) NULL,
    [Version]                VARCHAR (20)  NULL,
    [isClustered]            BIT           NULL,
    [MaxMemory]              BIGINT        NULL,
    [MinMemory]              INT           NULL,
    [DateCreated]            DATETIME      CONSTRAINT [c_default_datecreated] DEFAULT (getdate()) NULL,
    [ServiceAccount]         VARCHAR (60)  NULL,
    [DateUpdated]            DATETIME      CONSTRAINT [c_default_InstanceUpdateDate] DEFAULT (getdate()) NULL,
    [MonitorDatabases]       BIT           CONSTRAINT [c_default_monitordatabases] DEFAULT ((1)) NULL,
    [MonitorBlocking]        BIT           CONSTRAINT [c_default_MonitorBlocking] DEFAULT ((1)) NULL,
    [Criticality]            TINYINT       CONSTRAINT [c_default_Criticality] DEFAULT ((1)) NULL,
    [SSAS]                   BIT           NULL,
    [SSRS]                   BIT           NULL,
    [Deleted]                BIT           NULL,
    [DateDeleted]            DATETIME      NULL,
    [ProductLevel]           VARCHAR (10)  NULL,
    [PingStatus]             BIT           NULL,
    [SSASStatus]             VARCHAR (20)  NULL,
    [SSRSStatus]             VARCHAR (20)  NULL,
    [AgentStatus]            VARCHAR (20)  NULL,
    [MonitorWaitStats]       BIT           NULL,
    [HasBaseline]            BIT           NULL,
    [BaselineStartDate]      DATETIME      NULL,
    [HasWaitsBaseline]       BIT           NULL,
    [WaitsBaselineStartDate] DATETIME      NULL,
    CONSTRAINT [pk_monitoredinstances] PRIMARY KEY CLUSTERED ([InstanceID] ASC),
    CONSTRAINT [chk_InstanceEnvironment] CHECK ([Environment]='QA' OR [Environment]='DEVELOPMENT' OR [Environment]='PRODUCTION'),
    CONSTRAINT [uc_instancename] UNIQUE NONCLUSTERED ([InstanceName] ASC)
);

