CREATE TABLE [dbo].[MonitoredDatabases] (
    [DatabaseID]           INT           IDENTITY (1, 1) NOT NULL,
    [ServerID]             INT           NULL,
    [InstanceID]           INT           NOT NULL,
    [DatabaseName]         VARCHAR (128) NOT NULL,
    [CreationDate]         DATETIME      NULL,
    [CompatibilityLevel]   INT           NULL,
    [Collation]            VARCHAR (60)  NULL,
    [Size]                 FLOAT (53)    NULL,
    [DataSpaceUsage]       FLOAT (53)    NULL,
    [IndexSpaceUsage]      FLOAT (53)    NULL,
    [SpaceAvailable]       FLOAT (53)    NULL,
    [RecoveryModel]        VARCHAR (25)  NULL,
    [AutoClose]            BIT           NULL,
    [AutoShrink]           BIT           NULL,
    [ReadOnly]             BIT           NULL,
    [PageVerify]           VARCHAR (25)  NULL,
    [Owner]                VARCHAR (60)  NULL,
    [DateCreated]          DATETIME      CONSTRAINT [c_default_DB_DateCreated] DEFAULT (getdate()) NULL,
    [Dateupdated]          DATETIME      CONSTRAINT [c_default_DatabasesUpdateDate] DEFAULT (getdate()) NULL,
    [MonitorDatabaseFiles] BIT           CONSTRAINT [c_default_databasefiles] DEFAULT ((1)) NULL,
    [Status]               VARCHAR (60)  NULL,
    [Deleted]              BIT           CONSTRAINT [c_Default_Deleted] DEFAULT ((0)) NULL,
    [FBThreshold]          INT           CONSTRAINT [c_Default_FBThreshold] DEFAULT ((1440)) NULL,
    [FullBackupFlag]       BIT           CONSTRAINT [c_Default_FullBackupFlag] DEFAULT ((1)) NULL,
    [DBThreshold]          INT           CONSTRAINT [c_Default_DBThreshold] DEFAULT ((1440)) NULL,
    [DiffBackupFlag]       BIT           CONSTRAINT [c_Default_DiffBackupFlag] DEFAULT ((0)) NULL,
    [TBThreshold]          INT           CONSTRAINT [c_Default_TBThreshold] DEFAULT ((40)) NULL,
    [TranBackupFlag]       AS            (case when [RecoveryModel]='SIMPLE' then (0) else (1) end),
    [DateDeleted]          DATETIME      NULL,
    [DatabaseGUID]         VARCHAR (36)  NULL,
    [AvailabilityGroupID]  INT           NULL,
    CONSTRAINT [pk_monitoreddatabases] PRIMARY KEY CLUSTERED ([DatabaseID] ASC)
);

