CREATE TABLE [dbo].[MonitoredServers] (
    [ServerID]               INT           IDENTITY (1, 1) NOT NULL,
    [ServerName]             VARCHAR (128) NOT NULL,
    [Environment]            VARCHAR (60)  NULL,
    [MonitorServer]          BIT           CONSTRAINT [c_monitorServers] DEFAULT ((1)) NULL,
    [TotalMemory]            BIGINT        NULL,
    [Manufacturer]           VARCHAR (128) NULL,
    [Model]                  VARCHAR (128) NULL,
    [IPAddress]              VARCHAR (15)  NULL,
    [OperatingSystem]        VARCHAR (128) NULL,
    [BitLevel]               CHAR (2)      NULL,
    [DateInstalled]          DATETIME      NULL,
    [NumberofProcessors]     TINYINT       NULL,
    [NumberofProcessorCores] TINYINT       NULL,
    [ProcessorClockSpeed]    SMALLINT      NULL,
    [DateCreated]            DATETIME      CONSTRAINT [c_default_CreateDate] DEFAULT (getdate()) NULL,
    [DateUpdated]            DATETIME      CONSTRAINT [c_default_UpdateDate] DEFAULT (getdate()) NULL,
    [DateLastBoot]           DATETIME      NULL,
    [MonitorDrives]          BIT           CONSTRAINT [c_monitorDrives] DEFAULT ((1)) NULL,
    [PingStatus]             BIT           NULL,
    [Deleted]                BIT           NULL,
    [DateDeleted]            DATETIME      NULL,
    [IsVirtualServerName]    BIT           NULL,
    [HasBaseline]            BIT           NULL,
    [BaselineStartDate]      DATETIME      NULL,
    CONSTRAINT [pk_monitoredservers] PRIMARY KEY CLUSTERED ([ServerID] ASC),
    CONSTRAINT [chk_ServerEnvironment] CHECK ([Environment]='QA' OR [Environment]='DEVELOPMENT' OR [Environment]='PRODUCTION'),
    CONSTRAINT [uc_servername] UNIQUE NONCLUSTERED ([ServerName] ASC)
);

